### PR TITLE
Split MkFitInput{Converter,Wrapper} to MkFitHit{Converter,Wrapper} and MkFitSeed{Converter,Wrapper}

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Technical split of functionality as discussed in meeting(s), not change in functionality.

#### PR validation:

DQM histograms of workflow 11634.7 are equal before and after this PR.

### CODE REVIEW

**Comment by makortel** [comment]
@slava77 Could you take a look?
FYI @tresreid

**Comment by makortel** [comment]
@slava77 Do you want to take a look or shall I just merge?

**Comment by slava77** [comment]
> @slava77 Do you want to take a look or shall I just merge?

I thought I would manage to check this locally, but it did not happen.
Visually, it looks fine (which doesn't mean there will be no comments when it makes it to the cms-sw repo).
So, go ahead with merging.

**Comment by makortel** [comment]
> (which doesn't mean there will be no comments when it makes it to the cms-sw repo)

Agreed. And the hit side is anyway going to evolve in the near(?) future.

**Pull request merged**
