### PR TITLE
Reinactment of 135 CMMSW PR -- Prop to plane pr

### PR DESCRIPTION
**Pull request by osschar**
This is local / trackreco version of CMSSW PR 43146 -- cms-sw/cmssw#43146

There are some differences observed in MTV:
http://uaf-10.t2.ucsd.edu/~legianni/plots_compare_propToPlane_PRVersion/
To zero-th approximation:
* improved FR in high-purity tracks
* worse FR and eff in low-pT iterations

Assumption is that material effect improvements (beyond those if-confied out) lead to this.

### CODE REVIEW

**Comment by leonardogiannini** [comment]
> This is local / trackreco version of CMSSW PR 43146 -- [cms-sw#43146](https://github.com/cms-sw/cmssw/pull/43146)
> 
> There are some differences observed in MTV: http://uaf-10.t2.ucsd.edu/~legianni/plots_compare_propToPlane_PRVersion/ To zero-th approximation:
> 
> * improved FR in high-purity tracks
> * worse FR and eff in low-pT iterations
> 
> Assumption is that material effect improvements (beyond those if-confied out) lead to this.

low pT iterations are not using mkFit (we have the usual 4+1 iterations running), so they are reabsorbing hits (?)

it would be good to know where the changes come from, but they don't look problematic

**Comment by leonardogiannini** [comment]
this branch should have the material reverted https://github.com/trackreco/cmssw/commits/prop-to-plane-pr-mt1 
but the plots look very similar http://uaf-10.t2.ucsd.edu/~legianni/plots_compare_propToPlane_PRVersion2

@cerati @osschar

**Comment by cerati** [comment]
I think the other change is that in propagateHelixToRMPlex we now apply material effects after error propagation (instead of before). See that the following lines have moved up:
    MPlexLL temp;
    MultHelixProp(errorProp, outErr, temp);
    MultHelixPropTransp(errorProp, temp, outErr);

**Comment by leonardogiannini** [comment]
thanks Giuseppe for taking a look. it seems like swapping back these three lines in prop to R and prop to Z makes the comparisons much more even (not exactly the same)

see black vs blue here
http://uaf-10.t2.ucsd.edu/~legianni/plots_compare_propToPlane_PRVersion4/

**Comment by cerati** [comment]
please also take this commit: https://github.com/cerati/cmssw/commit/8911437cea06c5d407f0623b5d309d92f70ac419

**Comment by leonardogiannini** [comment]
As discussed this morning, I made some checks on the non mkFit iterations with the swap of the material effect in propToR and propToZ

I am checking the effect on single iterations while the rest is done with CKF 
You can check the single iteration with CKF (blue), original mkFit (red), branch https://github.com/trackreco/cmssw/tree/prop-to-plane-pr-mt1 (black) in 
http://uaf-10.t2.ucsd.edu/~legianni/plots_material_otherIterations/

some improvements are present in the low pt quadruplet at build level, but still not matching CKF 
image

low pT triplet for some reason is better and could maybe be tuned
image

pixelLess has some small improvements
image

**Comment by slava77** [comment]
I resynced our fork after the layers PR was merged to see the conflict here as well.

**Comment by slava77** [comment]
@osschar 
we were talking in the mkfit meeting what's missing for this PR review.
There was a comment to cleanup some commented out code.
Were you going to take care of that or waiting for more comments from the PR review?

**Pull request merged**
