### PR TITLE
Forward port not-in-official-CMSSW mkFit developments to 11_2_0_pre8

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Should cover https://github.com/trackreco/cmssw/pull/3 plus a customize function to customize HLT iter0 to use mkFit and its use in 11634.7 step2.

The included reco and HLT test files (in `RecoTracker/MkFit/test`) are directly from 10_4_0_patch1, and therefore could be broken. I did not test them. I'm not sure if it is worth to do anything for them before we have new common samples in 11_2.

#### PR validation:

`runTheMatrix.py -l 11634.7` runs in CMSSW_11_2_0_pre8.

### CODE REVIEW

**Comment by makortel** [comment]
@slava77 Please take a look.

**Comment by makortel** [comment]
@slava77 any comments, or shall I just merge?

**Comment by slava77** [comment]
> @slava77 any comments, or shall I just merge?

I didn't get to this yet

**Comment by slava77** [comment]
> @slava77 any comments, or shall I just merge?

from a visual inspection, the mkFit converter and geometry look good.

I did not make much effort checking the HLT piece; does it still run?

**Comment by makortel** [comment]
> I did not make much effort checking the HLT piece; does it still run?

It runs, and gets tested in the step 2 of 11634.7 .

**Comment by slava77** [comment]
> > I did not make much effort checking the HLT piece; does it still run?
> 
> It runs, and gets tested in the step 2 of 11634.7 .

I meant RecoTracker/MkFit/test/hlt_cfg.py and related parts in RecoTracker/MkFit/test

**Comment by makortel** [comment]
> > I meant RecoTracker/MkFit/test/hlt_cfg.py and related parts in RecoTracker/MkFit/test
> 
> if these parts are broken, perhaps it's worthwhile to decouple to another PR.

Those are likely broken, I did not test. Just to check I understood, are you suggesting to take them out of this PR? (I don't disagree, in that case I'd probably open another PR with them to keep them somehow around)

**Comment by slava77** [comment]
> Those are likely broken, I did not test. Just to check I understood, are you suggesting to take them out of this PR? (I don't disagree, in that case I'd probably open another PR with them to keep them somehow around)

yes, I meant to have them in a separate PR (if still needed)

**Comment by makortel** [comment]
> > Those are likely broken, I did not test. Just to check I understood, are you suggesting to take them out of this PR? (I don't disagree, in that case I'd probably open another PR with them to keep them somehow around)
> 
> yes, I meant to have them in a separate PR (if still needed)

Done now (was really about dropping last 8 commits).

**Comment by makortel** [comment]
@slava77 I suppose we could merge this PR now?

**Comment by slava77** [comment]
> @slava77 I suppose we could merge this PR now?

sure, go ahead

**Pull request merged**
