### PR TITLE
Enable backward search in pixelLessStep and tobTecStep

### PR DESCRIPTION
**Pull request by leonardogiannini**
#### PR description:

modified json files and RecoTracker/MkFit/plugins/createPhase1TrackerGeometry.cc to accommodate backward search in PR 345 https://github.com/trackreco/mkFit/pull/345

### CODE REVIEW

**Comment by leonardogiannini** [comment]
I just realized I need to add a few extra lines and then validate again. I will do it very soon.

**Comment by leonardogiannini** [comment]
the code should be ok
I also validated it here http://uaf-10.t2.ucsd.edu/~legianni/plots_bsearch_valid/ switching on only the pixelLess and tobTec iterations in mkFit. 

Interestingly
http://uaf-10.t2.ucsd.edu/~legianni/plots_bsearch_valid/plots_building_pixelLessStep/hitsLayers.pdf
http://uaf-10.t2.ucsd.edu/~legianni/plots_bsearch_valid/plots_building_tobTecStep/hitsLayers.pdf

seem to be closer to CKF than the previous validation analogous plots here http://uaf-10.t2.ucsd.edu/~legianni/QCD-etc_testing/plots_2nd+3rd-att
(seems like the #holes cut is relaxed?)

anyway this should be ready for merging

**Comment by makortel** [comment]
Looks good by eye, I'll merge it after trackreco/mkFit#345 gets merged.

**Comment by mmasciov** [comment]
FYI: trackreco/mkFit#345 is good and just merged.

**Pull request merged**
